// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (license === "BOOST") {
    licenseBadge = '![badge](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)\n';
  }
  if (license === "Apache") {
    licenseBadge = '![badge](https://img.shields.io/badge/License-Apache_2.0-blue.svg)\n';
  }
  if (license === "MIT") {
    licenseBadge = '![badge](https://img.shields.io/badge/License-MIT-yellow.svg)\n';
  }
  else {
    " ";
  }
  return licenseBadge;
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if (license === "BOOST") {
    licenseLink = '(https://www.boost.org/LICENSE_1_0.txt)\n';
  }
  if (license === "Apache") {
    licenseLink = '(https://opensource.org/licenses/Apache-2.0)\n';
  }
  if (license === "MIT") {
    licenseLink = '(https://opensource.org/licenses/MIT)\n';
  }
  else {
    " ";
  }
  return licenseLink;

}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string 

function renderLicenseSection(license) {
  if (license === "BOOST") {
    licenseSection = 
    `Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:
    
    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE. \n`;
  }
  if (license === "Apache") {
    licenseSection = 
    `Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
 
      http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.\n`;
  }
  if (license === "MIT") {
    licenseSection = 
    `Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal 
    in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR 
    ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH 
    THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n`;
  }
  else {
    " ";
  }
  return licenseSection;
}

// TODO: Create a function to generate markdown for README
// Creates markdown for README file
function generateMarkdown(data) {
  let content = ' '

  content += `
  
  # ${data.title}

  ## Table of Contents:
  
  <a href="#description">Description</a> \n
  <a href="#installation">Installation</a> \n
  <a href="#usage">Usage</a> \n
  <a href="#credits">Credits</a> \n
  <a href="#license">License</a> \n
  <a href="#testing">Testing</a> \n
  <a href="#questions">Questions</a> \n


  ## Description
  ${data.description}

  ## Installation
  ${data.installation}
           
  ## Usage
  ${data.usage}

  ## Credits
  ${data.credits}

  ## License
  ${data.license}
  ${renderLicenseBadge(data.license)}
  ${renderLicenseLink(data.license)}
  ${renderLicenseSection(data.license)}

  ## Testing
  ${data.test}
  ` 
  
  
  
  content += `## Questions
  This was made by ${data.username}. Any questions can be sent to ${data.email}.
  You can find more at (https://github.com/${data.username})
  `;
  
  
  return content;
};

module.exports = generateMarkdown;
